% Generated by MATLAB(R) 9.11 (R2021b) and Sensor Fusion and Tracking Toolbox 2.2 (R2021b).
% Generated on: 14-Mar-2022 16:33:25
clear; clc
i=1;
scenario = createScenario();

% Configure your tracker here:

% Add a trackPlotter here:

% Main simulation loop
while advance(scenario) 
    % get positions
    truePosition = readData(scenario);
    
    orientation(i,:) = scenario.Platforms{1}.Orientation;
    rad2deg(quat2eul(scenario.Platforms{1}.Trajectory.Orientation))
    scenario.Platforms{1}.Trajectory.Waypoints
    i = i+1;
end


function position = readData(scenario)

truePoses = platformPoses(scenario);
position = vertcat(truePoses(:).Position);
end

function scenario = createScenario
% Create Scenario
scenario = trackingScenario;
scenario.StopTime = Inf;
scenario.UpdateRate = 500;


% Create platforms
Plane = platform(scenario,'ClassID',1);

Plane.Trajectory = waypointTrajectory( ...
    [0 0 0;-0.0002 -43.8569 0], ...
    [0;0.175427600001824], ...
    'Course', [-90.0002612851319;-90.0002612851319], ...
    'GroundSpeed', [250;0], ...
    'ClimbRate', [0;0], ...
    'AutoPitch', true, ...
    'AutoBank', true);

end
